version: '3.7'
services:
  nginx:
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/var/www/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/confs/:/etc/nginx/conf.d/
      - ./docker/nginx/logs:/var/log/nginx/
      - /etc/letsencrypt/live/taptar.ru/fullchain.pem:/etc/nginx/ssl/fullchain.pem # SSL
      - /etc/letsencrypt/live/taptar.ru/privkey.pem:/etc/nginx/ssl/privkey.pem
      - /etc/letsencrypt/ssl-params.conf:/etc/nginx/ssl/options-ssl-nginx.conf
      - /etc/letsencrypt/ssl-dhparams.pem:/etc/nginx/ssl/ssl-dhparams.pem
    ports:
      - 80:80
      - 443:443
    links:
      - php-fpm
      - echo-server

  mariadb:
    image: mariadb:10.6
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=rahman
      - MYSQL_PASSWORD=rahman
      - MYSQL_DATABASE=app
      - TZ=Europe/Moscow
    volumes:
      - ./docker/running/mysql:/var/lib/mysql/
    ports:
      - "33006:3306"

  php-fpm:
    build:
      context: ./
      dockerfile: ./docker/php-fpm/Dockerfile
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/backend
      - ./docker/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php-fpm/logs/:/var/log/
    #ports:
    #- "9001:9001"

  php-cli:
    build:
      context: ./
      dockerfile: ./docker/php-cli/Dockerfile
      args:
        WWWUSER: ${USER}
    restart: unless-stopped
    tty: true
    user: ${USER}
    volumes:
      - ./backend:/var/www/backend
      - ./docker:/var/www/running-docker
    #ports:
    #- "9001:9001"
    command:
      - /bin/sh
      - -c
      - supervisord -c /var/www/running-docker/php-cli/supervisor/supervisord.conf && supervisorctl start all

  npm:
    build:
      context: ./
      dockerfile: ./docker/npm/Dockerfile
    volumes:
      - ./frontend:/var/www/frontend
    tty: true
    restart: unless-stopped
#    ports:
#      - "3000:3000"

  echo-server:
    build:
      context: ./
      dockerfile: ./docker/echo-server/Dockerfile
    environment:
      - LARAVEL_ECHO_SERVER_AUTH_HOST=https://api.taptar.ru
    volumes:
      - ./backend:/var/www/backend
      - ./docker:/var/www/running-docker
    command:
      - /bin/sh
      - -c
      - supervisord -c /var/www/running-docker/echo-server/supervisor/supervisord.conf && supervisorctl start all
    tty: true
    restart: unless-stopped
    links:
      - redis

  redis:
    image: redis
    ports:
      - "63799:6379"
